# Generated by Django 4.1.1 on 2022-10-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=50)),
                ('spare_money', models.CharField(max_length=50)),
                ('free_time', models.CharField(max_length=50)),
                ('fitness', models.CharField(choices=[('poor', 'POOR'), ('ok', 'OK'), ('good', 'GOOD'), ('excellent', 'EXCELLENT')], default='poor', max_length=50)),
            ],
        ),
    ]
